<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="7BB9LQ2" name="com.ca.tds.main.TDSPreAreq_TC" tests="12" failures="12" timestamp="20 Jan 2020 13:01:42 GMT" time="9.502" errors="0">
  <testcase name="testArequestAPI" time="0.618" classname="com.ca.tds.main.TDSPreAreq_TC">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [CADS] but found [DsReferenceNumber],
	expected [ABCDEF987654321] but found [DsReferenceNumber],
	expected [Y] but found [U]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [CADS] but found [DsReferenceNumber],
expected [ABCDEF987654321] but found [DsReferenceNumber],
expected [Y] but found [U]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.ca.tds.main.TDSPreAreq_TC.testArequestAPI(TDSPreAreq_TC.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testArequestAPI -->
  <testcase name="testArequestAPI" time="0.703" classname="com.ca.tds.main.TDSPreAreq_TC">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [CADS] but found [DsReferenceNumber],
	expected [C] but found [Y]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [CADS] but found [DsReferenceNumber],
expected [C] but found [Y]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.ca.tds.main.TDSPreAreq_TC.testArequestAPI(TDSPreAreq_TC.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testArequestAPI -->
  <testcase name="testArequestAPI" time="0.684" classname="com.ca.tds.main.TDSPreAreq_TC">
    <failure type="java.lang.AssertionError" message="errorComponent : S, errorCode : 403, errorDescription : No DS configured for this PAN - Not found in Card Range Cache, errorDetail :  Internal Trasient error occured for this transaction , threeDSServerTransID : 320a88e6-f1d2-4225-9739-d350992b9b33">
      <![CDATA[java.lang.AssertionError: errorComponent : S, errorCode : 403, errorDescription : No DS configured for this PAN - Not found in Card Range Cache, errorDetail :  Internal Trasient error occured for this transaction , threeDSServerTransID : 320a88e6-f1d2-4225-9739-d350992b9b33
at org.testng.Assert.fail(Assert.java:96)
at com.ca.tds.main.TDSPreAreq_TC.testArequestAPI(TDSPreAreq_TC.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testArequestAPI -->
  <testcase name="testArequestAPI" time="0.730" classname="com.ca.tds.main.TDSPreAreq_TC">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [CADS] but found [DsReferenceNumber],
	expected [ABCDEF987654321] but found [DsReferenceNumber],
	expected [Y] but found [U]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [CADS] but found [DsReferenceNumber],
expected [ABCDEF987654321] but found [DsReferenceNumber],
expected [Y] but found [U]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.ca.tds.main.TDSPreAreq_TC.testArequestAPI(TDSPreAreq_TC.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testArequestAPI -->
  <testcase name="testArequestAPI" time="0.671" classname="com.ca.tds.main.TDSPreAreq_TC">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [CADS] but found [DsReferenceNumber]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [CADS] but found [DsReferenceNumber]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.ca.tds.main.TDSPreAreq_TC.testArequestAPI(TDSPreAreq_TC.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testArequestAPI -->
  <testcase name="testArequestAPI" time="0.623" classname="com.ca.tds.main.TDSPreAreq_TC">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [CADS] but found [DsReferenceNumber],
	expected [ABCDEF987654321] but found [DsReferenceNumber],
	expected [C] but found [U]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [CADS] but found [DsReferenceNumber],
expected [ABCDEF987654321] but found [DsReferenceNumber],
expected [C] but found [U]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.ca.tds.main.TDSPreAreq_TC.testArequestAPI(TDSPreAreq_TC.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testArequestAPI -->
  <testcase name="testArequestAPI" time="0.573" classname="com.ca.tds.main.TDSPreAreq_TC">
    <failure type="java.lang.AssertionError" message="errorComponent : S, errorCode : 203, errorDescription : CA Merchant Server:: Invalid Format  for one of the  Element Found in the message , errorDetail : threeDSServerTransID, threeDSServerTransID : e5d9b124-580a-4913-afe7-b3c056597b50">
      <![CDATA[java.lang.AssertionError: errorComponent : S, errorCode : 203, errorDescription : CA Merchant Server:: Invalid Format  for one of the  Element Found in the message , errorDetail : threeDSServerTransID, threeDSServerTransID : e5d9b124-580a-4913-afe7-b3c056597b50
at org.testng.Assert.fail(Assert.java:96)
at com.ca.tds.main.TDSPreAreq_TC.testArequestAPI(TDSPreAreq_TC.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testArequestAPI -->
  <testcase name="testArequestAPI" time="0.695" classname="com.ca.tds.main.TDSPreAreq_TC">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [CADS] but found [DsReferenceNumber],
	expected [ABCDEF987654321] but found [DsReferenceNumber],
	expected [C] but found [U]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [CADS] but found [DsReferenceNumber],
expected [ABCDEF987654321] but found [DsReferenceNumber],
expected [C] but found [U]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.ca.tds.main.TDSPreAreq_TC.testArequestAPI(TDSPreAreq_TC.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testArequestAPI -->
  <testcase name="testArequestAPI" time="2.169" classname="com.ca.tds.main.TDSPreAreq_TC">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [CADS] but found [DsReferenceNumber]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [CADS] but found [DsReferenceNumber]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.ca.tds.main.TDSPreAreq_TC.testArequestAPI(TDSPreAreq_TC.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testArequestAPI -->
  <testcase name="testArequestAPI" time="0.733" classname="com.ca.tds.main.TDSPreAreq_TC">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [CADS] but found [DsReferenceNumber],
	expected [C] but found [Y]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [CADS] but found [DsReferenceNumber],
expected [C] but found [Y]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.ca.tds.main.TDSPreAreq_TC.testArequestAPI(TDSPreAreq_TC.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testArequestAPI -->
  <testcase name="testArequestAPI" time="0.593" classname="com.ca.tds.main.TDSPreAreq_TC">
    <failure type="java.lang.AssertionError" message="errorComponent : S, errorCode : 203, errorDescription : CA Merchant Server:: Invalid Format  for one of the  Element Found in the message , errorDetail : threeDSServerTransID, threeDSServerTransID : 85deb90f-2eeb-4bcd-8cdd-376adb9b4a5c">
      <![CDATA[java.lang.AssertionError: errorComponent : S, errorCode : 203, errorDescription : CA Merchant Server:: Invalid Format  for one of the  Element Found in the message , errorDetail : threeDSServerTransID, threeDSServerTransID : 85deb90f-2eeb-4bcd-8cdd-376adb9b4a5c
at org.testng.Assert.fail(Assert.java:96)
at com.ca.tds.main.TDSPreAreq_TC.testArequestAPI(TDSPreAreq_TC.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testArequestAPI -->
  <testcase name="testArequestAPI" time="0.710" classname="com.ca.tds.main.TDSPreAreq_TC">
    <failure type="java.lang.AssertionError" message="errorComponent : S, errorCode : 403, errorDescription : No DS configured for this PAN - Not found in Card Range Cache, errorDetail :  Internal Trasient error occured for this transaction , threeDSServerTransID : fd138bec-00ce-4a5a-a426-eae8d02ff45a">
      <![CDATA[java.lang.AssertionError: errorComponent : S, errorCode : 403, errorDescription : No DS configured for this PAN - Not found in Card Range Cache, errorDetail :  Internal Trasient error occured for this transaction , threeDSServerTransID : fd138bec-00ce-4a5a-a426-eae8d02ff45a
at org.testng.Assert.fail(Assert.java:96)
at com.ca.tds.main.TDSPreAreq_TC.testArequestAPI(TDSPreAreq_TC.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testArequestAPI -->
</testsuite> <!-- com.ca.tds.main.TDSPreAreq_TC -->
